# This is a basic workflow to help you get started with Actions

name: Repo Sync

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - run: git push --mirror git@bitbucket.org:osoner/countly-server.git
