name: Sync multiple branches
on:
  workflow_dispatch:
    inputs:
      destination:
        description: 'Destination branch'
        required: true
        default: "next"
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: "$DEST"
          github_token: ${{ secrets.BRANCH_SYNC }}
        env:
          DEST: ${{ inputs.destination }}
